zoneNum = 4
run_folder_name= "/media/reddi-rtx/KINGSTON/FARSI_results/1_1_1_for_paper_07-31"
run_folder_name="/home/reddi-rtx/FARSI_related_stuff/Project_FARSI_4/data_collection/data/simple_run/08-01_13-22_12"
run_folder_name="/media/reddi-rtx/KINGSTON/FARSI_results/scaling_of_1_2_4_across_all_budgets_07-31"
run_folder_name="/media/reddi-rtx/KINGSTON/FARSI_results/blind_study/blind_version/blind_combined/"
run_folder_name="/media/reddi-rtx/KINGSTON/FARSI_results/blind_study/blind_version/blind_vs_arch_ware"
run_folder_name="/media/reddi-rtx/KINGSTON/FARSI_results/blind_study_smart_krnel_selection/blind_vs_arch_ware"
run_folder_name ="/home/reddi-rtx/FARSI_related_stuff/Project_FARSI_4/data_collection/data/simple_run/aggregate_data"
#run_folder_name ="/home/reddi-rtx/FARSI_related_stuff/Project_FARSI_4/data_collection/data/simple_run/08-02_01-38_26/"
#run_folder_name ="/media/reddi-rtx/KINGSTON/FARSI_results/optimal_budgetting_problem_08_1"
run_folder_name = "/Users/behzadboro/FARSI_related_stuff/FARSI_results/1_1_1_for_paper_07-31"
run_folder_name = "/home/reddi-rtx/FARSI_related_stuff/Project_FARSI_TECS/Project_FARSI_6/data_collection/data/simple_run/final_03-04_19-58_52"
heuristic_comparison_folder = "/home/reddi-rtx/FARSI_related_stuff/Project_FARSI_TECS/Project_FARSI_6/data_collection/data/simple_run/blah_"
#heuristic_comparison_folder = "/media/reddi-rtx/Samsung USB/FARSI_results_5000"
heuristic_comparison_folder = "/media/reddi-rtx/Samsung USB/moos_with_ctr_greedy_collection"
#heuristic_comparison_folder = "/media/reddi-rtx/Samsung USB/FARSI_results"
#heuristic_comparison_folder = "/media/reddi-rtx/Samsung USB/SA_metropolis_criteria"
#heuristic_comparison_folder = "/media/reddi-rtx/Samsung USB/SA_modified_randomness"
#heuristic_comparison_folder = "/media/reddi-rtx/Samsung USB/FARSI_5000_all_the_way"
#run_folder_name = "/home/yingj4/Desktop/FARSI_results/arch-aware-vs-random/all_workloads_together"
#top_result_folder = "/home/yingj4/Desktop/FARSI_results/arch-aware-vs-random"
heuristic_comparison_folder = "/media/reddi-rtx/Samsung USB/compare_heuristics"  # for comparing FARSI vs SA vs moos
heuristic_comparison_folder = "/media/reddi-rtx/Samsung USB/heuristic_scaling" # just FARSI for different task count/and budget
heuristic_comparison_folder = "/media/reddi-rtx/Samsung USB/compare_heuristic_worse_version_1" # for comparing FARSI vs SA vs greedy-ctr of moos
#heuristic_comparison_folder = "/media/reddi-rtx/Samsung USB/compare_heuristic_worse_version_2" # for comparing FARSI vs SA vs closest to SA of moos

top_result_folder = "/home/reddi-rtx/FARSI_related_stuff/Project_FARSI_4/data_collection/data/simple_run"
ignore_file_names = ["README.md", "figures", "cross_workloads", "single_workload", "3D", "budget_optimality", "panda_study", "pie_chart", "verification"]
#plot_list = ["cross_workloads", "single_workload","plot_3d", "pandas_plots", "budget_optimality"]
plot_list = ["cross_workloads"]#"cross_workloads", "single_workload"]
plot_list = ["heuristic_comparison"]#"cross_workloads", "single_workload"]
#plot_list = ["heuristic_scaling"]#"cross_workloads", "single_workload"]
#plot_list = ["pareto_studies"]#"cross_workloads", "single_workload"]
draw_for_paper = False